# Generated by Django 5.0.6 on 2024-06-21 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_alter_mailingsettings_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingmessage',
            options={'permissions': [('can_view_mailing', 'Права просматривать сообщения'), ('can_delete_mailing', 'Права блокировать сообщения')], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
