# Generated by Django 5.0.6 on 2024-06-21 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_alter_mailingmessage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingmessage',
            options={'permissions': [('can_view_mailingmessage', 'Can view MailingMessage'), ('can_edit_mailingmessage', 'Can edit MailingMessage'), ('can_delete_mailingmessage', 'Can delete MailingMessage')], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
