# Generated by Django 5.0.6 on 2024-06-21 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0008_alter_mailingmessage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingmessage',
            options={'permissions': [('can_view_message', 'Can view message'), ('can_edit_message', 'Can edit message'), ('can_delete_message', 'Can delete message')], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
