# Generated by Django 5.0.6 on 2024-06-21 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0009_alter_mailingmessage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingsettings',
            options={'permissions': [('can_view_malling', 'Can view malling'), ('can_edit_malling', 'Can edit malling'), ('can_delete_maslling', 'Can delete malling')], 'verbose_name': 'Настройка рассылки', 'verbose_name_plural': 'Настройки рассылки'},
        ),
    ]
