# Generated by Django 5.0.6 on 2024-06-21 21:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0011_alter_mailingsettings_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingsettings',
            name='last_sent_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Поле для отслеживания периода'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mailingsettings',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Конец рассылки'),
            preserve_default=False,
        ),
    ]
