# Generated by Django 5.0.6 on 2024-06-21 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipient', '0003_alter_recipient_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipient',
            options={'permissions': [('can_view_client', 'Права просматривать клиентов'), ('can_delete_client', 'Права блокировать клиентов'), ('can_edit_client', 'Права изменить клиентов')], 'verbose_name': 'Получатель', 'verbose_name_plural': 'Получатели'},
        ),
    ]
