# Generated by Django 5.0.6 on 2024-06-21 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipient', '0004_alter_recipient_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipient',
            options={'permissions': [('can_view_client', 'Can view recipient'), ('can_delete_client', 'Can delete recipient'), ('can_edit_client', 'Can edit recipient')], 'verbose_name': 'Получатель', 'verbose_name_plural': 'Получатели'},
        ),
    ]
